MODEL:
  NAME: "LitCRNN"
  NUM_CLASSES: 10
  LOAD: "NONE"
  CRNN:
    INCLUDE_TOP: True
DATASET:
  NAME: "UrbanSounds8K"
  ANNOTATION_PATH: '../datasets/UrbanSound8K/metadata/UrbanSound8K.csv'
  FILE_PATH: '../datasets/UrbanSound8K/audio/'
  VAL_FOLD: 10
  WEIGHT: "NORMAL" #"SQUARED"
DATALOADER:
  BATCH_SIZE: 12
  NUM_WORKERS: 20
SOLVER:
  LOG_PATH: '../logs/'
  NUM_GPUS: 1
  MAX_EPOCH: 30
  MIN_EPOCH: 10
  LEARNING_RATE: 0.01
  WEIGHT_DECAY: 0.001
  STEP_SIZE: 7
  GAMMA: 0.1
CHECKPOINT:
  SAVE_NAME: "crnn-us8k"
  SAVE_PATH: '../weights'
  SAVE_TOP_K: 1

