MODEL:
  NAME: "LitCRNN"
  NUM_CLASSES: 10
  CRNN:
    RANDOMISED_SMOOTHING: False
    INCLUDE_TOP: True
    INCLUDE_TRANSFORM: False
DATASET:
  NAME: "UrbanSounds8K"
  ANNOTATION_PATH: '../datasets/UrbanSound8K/metadata/UrbanSound8K.csv'
  FILE_PATH: '../datasets/UrbanSound8K/audio/'
  VAL_FOLD: 2
  WEIGHT: "None" #"SQUARED" #"NORMAL" #"None"
  AUGMENTATION: "none" #'random'
  NOISE_PATH: '../datasets/MUSAN/free-sound/'
DATALOADER:
  BATCH_SIZE: 12
  NUM_WORKERS: 20
TRANSFORM:
  HOP_LENGTH: 256
LOSS: 'cross_entropy'
SOLVER:
  LOG_PATH: '../logs/final/'
  NUM_GPUS: 1
  MAX_EPOCH: 125
  MIN_EPOCH: 1
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.01
  STEP_SIZE: 25
  SIGMA: 1
  GAMMA: 0.5
CHECKPOINT:
  SAVE_NAME: "crnn-us8k"
  SAVE_PATH: '../weights/final'
  SAVE_TOP_K: 1
ATTACK: False
