MODEL:
  NAME: "LitCRNN"
  NUM_CLASSES: 10
  CRNN:
    INCLUDE_TOP: True
    PAD_INPUT: 15
DATASET:
  NAME: "UrbanSound8K"
  CLIP_LENGTH: 176400
  ANNOTATION_PATH: '../datasets/UrbanSound8K/metadata/UrbanSound8K.csv'
  FILE_PATH: '../datasets/UrbanSound8K/audio/'
  VAL_FOLD: 10
DATALOADER:
  BATCH_SIZE: 12
  NUM_WORKERS: 20
  SHUFFLE_TRAIN: True
  SHUFFLE_TEST: False
SOLVER:
  LOG_PATH: '../logs/'
  NUM_GPUS: 1
  MAX_EPOCH: 20
  MIN_EPOCH: 10
  LEARNING_RATE: 0.01
  WEIGHT_DECAY: 0.001
CHECKPOINT:
  SAVE_NAME: "crnn"
  SAVE_PATH: '../weights'
  SAVE_TOP_K: 1

