MODEL:
  NAME: "LitCRNN"
  NUM_CLASSES: 10
  CRNN:
    RANDOMISED_SMOOTHING: True
    INCLUDE_TOP: True
    INCLUDE_TRANSFORM: False
DATASET:
  NAME: "UrbanSounds8K"
  ANNOTATION_PATH: '/nfs/students/winter-term-2020/project-1/datasets/UrbanSound8K/metadata/UrbanSound8K.csv'
  FILE_PATH: '/nfs/students/winter-term-2020/project-1/datasets/UrbanSound8K/audio/'
  VAL_FOLD: 10
  WEIGHT: "None" #"SQUARED" #"NORMAL" #"None"
DATALOADER:
  BATCH_SIZE: 12
  NUM_WORKERS: 20
TRANSFORM:
  HOP_LENGTH: 256
LOSS: 'cross_entropy'
SOLVER:
  LOG_PATH: '../logs/us8k/'
  NUM_GPUS: 1
  MAX_EPOCH: 125
  MIN_EPOCH: 1
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.01
  STEP_SIZE: 25
  SIGMA: 0.5
  GAMMA: 0.5
CHECKPOINT:
  SAVE_NAME: "crnn-us8k"
  SAVE_PATH: '../weights'
  SAVE_TOP_K: 1
ATTACK: True
