MODEL:
  NAME: "LitCRNN"
  NUM_CLASSES: 6
  CRNN:
    INCLUDE_TOP: True
DATASET:
  NAME: "BMW"
  ANNOTATION_PATH: '/nfs/students/winter-term-2020/project-1/datasets/BMW/meta/trimmed/bmw.csv'
  FOLDER_PATH: '/nfs/students/winter-term-2020/project-1/datasets/Brake_Noise_Jan20_trim'
  WEIGHT: "NORMAL" #"SQUARED" #"None"
  VAL_FOLD: 10
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 20
SOLVER:
  LOG_PATH: '../logs/week-5'
  NUM_GPUS: 1
  MAX_EPOCH: 5
  MIN_EPOCH: 1
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.001
  STEP_SIZE: 20
  GAMMA: 0.5
CHECKPOINT:
  SAVE_NAME: "crnn-bmw"
  SAVE_PATH: '../weights/week-5'
  SAVE_TOP_K: 1

