MODEL:
  NAME: "LitM11"
  NUM_CLASSES: 6
DATASET:
  NAME: "BMW"  
  ANNOTATION_PATH: '../datasets/BMW/meta/bmw.csv'
  FOLDER_PATH: '/nfs/students/winter-term-2020/project-1/datasets/Brake_Noise' 
  VAL_FOLD: 10
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 20
SOLVER:
  LOG_PATH: '../logs/m11'
  NUM_GPUS: 1
  MAX_EPOCH: 30
  MIN_EPOCH: 1
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.0001 #1e-4 in the paper
  STEP_SIZE: 7
  GAMMA: 0.1
CHECKPOINT:
  SAVE_NAME: "m11"
  SAVE_PATH: '../weights'
  SAVE_TOP_K: 1
