MODEL:
  NAME: "LitM11"
  NUM_CLASSES: 6
  LOAD: "/nfs/students/winter-term-2020/project-1/project-1/weights/m11-fold9-epoch=49-val_acc=0.817.ckpt" # "NONE"
DATASET:
  NAME: "BMW"
  ANNOTATION_PATH: '/nfs/students/winter-term-2020/project-1/datasets/BMW/meta/bmw.csv'
  FOLDER_PATH: '/nfs/students/winter-term-2020/project-1/datasets/Brake_Noise'
  VAL_FOLD: 10
  FOLDER_PATH_TRIM: '/nfs/students/winter-term-2020/project-1/datasets/Brake_Noise_Jan20_trim' # didnt add this to bmw.py
  WEIGHT: "NORMAL" #"SQUARED"
DATALOADER:
  BATCH_SIZE: 4
  NUM_WORKERS: 20
SOLVER:
  LOG_PATH: '../logs/m11/10-fold'
  NUM_GPUS: 1
  MAX_EPOCH: 100
  MIN_EPOCH: 1
  LEARNING_RATE: 0.000015984826253924876
  WEIGHT_DECAY: 0.000012743200395718975  #1e-4 in the paper
  STEP_SIZE: 7
  GAMMA: 0.1
CHECKPOINT:
  SAVE_NAME: "m11"
  SAVE_PATH: '../weights/load_m11-fold9-epoch=49-val_acc=0.817'
  SAVE_TOP_K: 1
