MODEL:
  NAME: "LitM18"
  NUM_CLASSES: 6
  SANITY_CHECK: 1 # to check if model is training properly or not. Number specifies the length of train dataloader
DATASET:
  NAME: "BMW"
  FOLDER_PATH: '/nfs/students/winter-term-2020/project-1/datasets/Brake_Noise'
  FOLDER_PATH_TRIM: '/nfs/students/winter-term-2020/project-1/datasets/Brake_Noise_Jan20_trim' # didn't add this to bmw.py
DATALOADER:
  BATCH_SIZE: 4
  NUM_WORKERS: 20
SOLVER:
  LOG_PATH: '../logs/'
  NUM_GPUS: 1
  MAX_EPOCH: 30
  MIN_EPOCH: 1
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.0000001 #1e-4 in the paper
  STEP_SIZE: 7
  GAMMA: 0.1
CHECKPOINT:
  SAVE_NAME: "m18"
  SAVE_PATH: '../weights'
  SAVE_TOP_K: 1
