MODEL:
  NAME: "LitM18"
  NUM_CLASSES: 6
DATASET:
  NAME: "BMW"  
  ANNOTATION_PATH: '../datasets/BMW/meta/bmw.csv'
  FOLDER_PATH: '/nfs/students/winter-term-2020/project-1/datasets/Brake_Noise'
  FOLDER_PATH_TRIM: '/nfs/students/winter-term-2020/project-1/datasets/Brake_Noise_Jan20_trim'
  WEIGHT: "NORMAL" #"SQUARED"
  VAL_FOLD: 10
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 20
SOLVER:
  LOG_PATH: '../logs/m18/'
  NUM_GPUS: 1
  MAX_EPOCH: 125
  MIN_EPOCH: 1
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.0001 # from the paper
  STEP_SIZE: 25
  GAMMA: 0.5
CHECKPOINT:
  SAVE_NAME: "m18"
  SAVE_PATH: '../weights/m18'
  SAVE_TOP_K: 1
